# Generated by Django 4.2.7 on 2023-12-01 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('racipe_name', models.CharField(max_length=200)),
                ('racipe_description', models.TextField()),
                ('racipe_image', models.ImageField(upload_to='recipe')),
            ],
        ),
    ]
